name: Makkah Bot Cloud

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        # تثبيت المكتبتين المطلوبتين فقط!
        run: pip install google-genai opencv-python-headless

      - name: Run Bot
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python monitor.py

      - name: Push Changes
        run: |
          git config --global user.name "Makkah-Bot"
          git config --global user.email "bot@github.com"
          git add status.json
          git commit -m "Direct Stream Update" || exit 0
          git push
