name: Makkah Bot Cloud

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install FFmpeg
        # هذه الخطوة لتثبيت البرنامج المفقود في السيرفر
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install google-genai

      - name: Run Bot
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python monitor.py

      - name: Push Changes
        run: |
          git config --global user.name "Makkah-Bot"
          git config --global user.email "bot@github.com"
          git add status.json
          git commit -m "Fix FFmpeg Installation" || exit 0
          git push
